### ISSUE TITLE
 No module named 'raft'

### ISSUE THREAD

**Issue by alexfredo** [volotat/SD-CN-Animation#1]
Hi I have a error when I try to run the script :
 C:\AUTOMATIC1111>py script.py
Traceback (most recent call last):
  File "C:\AUTOMATIC1111\script.py", line 15, in <module>
    from raft import RAFT
ModuleNotFoundError: No module named 'raft'

Apparently I need to install raft but how I add raft to automatic1111 ? thanks

**Comment by volotat** [comment]
No. You don't need to install raft in automatic1111. It should hook up the 'RAFT' repository when you clone 'SD-CN-Animation'. If it didn't happen for some reason, go to the 'SD-CN-Animation' folder, open CLI and do 'git clone https://github.com/princeton-vl/RAFT.git' command. It should create 'RAFT' folder with all the necessary scripts and it should work fine afterwards.

**Comment by alexfredo** [comment]
Thanks for raft it's works, but I have another problem when I run the script it's open a window that quickly close and I have just this message in the command : 0it [00:00, ?it/s]

**Comment by alexfredo** [comment]
in the script I need to write the format like that ? : 
INPUT_VIDEO = "C:\AUTOMATIC1111\INPUTVIDEO\1.mp4"
OUTPUT_VIDEO = "C:\AUTOMATIC1111\OUTPUTVIDEO\1.mp4"

**Comment by volotat** [comment]
Yeah. The format seems fine to me. I suspect It cannot find video file for some reason. Try to move it in  'SD-CN-Animation' folder and set INPUT_VIDEO = "1.mp4". Also make sure that the video is working in any videoplayer.

**Comment by alexfredo** [comment]
Ok it launched everything and after generate the first picture I have a error : 
OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
  1%|▋                                                                                 | 1/117 [00:08<16:53,  8.74s/it]
Traceback (most recent call last):
  File "C:\AUTOMATIC1111\SD-CN-Animation\script.py", line 234, in <module>
    _, alpha_mask, warped_styled = RAFT_estimate_flow_diff(prev_frame, frame, prev_frame_styled)
  File "C:\AUTOMATIC1111\SD-CN-Animation\script.py", line 100, in RAFT_estimate_flow_diff
    RAFT_model.load_state_dict(torch.load(args.model))
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'RAFT/models/raft-things.pth'


It's the video format not supported ?

**Comment by volotat** [comment]
Nope, It cannot find the 'raft-things.pth' model. I forget to mention it in the instruction, you have to set up the RAFT repository as it described here: https://github.com/princeton-vl/RAFT
Basically it just comes down to running "./download_models.sh" to download the models. I would suggest not to creating a special conda environment, but choose what is more convenient for you.

**Comment by alexfredo** [comment]
it's works ! but the picture become blurry and dark after few minutes here the first pictures : 
![00001](https://user-images.githubusercontent.com/24534698/230740487-c5926eeb-71d2-433c-b6ee-089a8f0e2e63.png)

and the last :
![00041](https://user-images.githubusercontent.com/24534698/230740498-b74c2c7f-3187-4557-aa22-306e3a597621.png)

**Comment by alexfredo** [comment]
Also it's generate the video but I have a error message display in the cmd of automatic1111 : Error running process: C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\AUTOMATIC1111\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 628, in process
    unit = self.parse_remote_call(p, unit, idx)

**Comment by alexfredo** [comment]
Do you know why it's become more and more darker after each render here another example : 
![00001](https://user-images.githubusercontent.com/24534698/230741106-5df177da-431f-48eb-9628-63b27f3cf1c3.png)
![00002](https://user-images.githubusercontent.com/24534698/230741107-d5966b2f-3ba0-407b-95d5-6f29ae89f322.png)
![00003](https://user-images.githubusercontent.com/24534698/230741108-4a50eb1f-e25d-4f29-8996-9d76e63350ca.png)
![00004](https://user-images.githubusercontent.com/24534698/230741111-199b8969-5fe3-42b9-84f7-c77b3694165e.png)
![00005](https://user-images.githubusercontent.com/24534698/230741112-4d8e0f42-2745-4a04-ad88-04735383661e.png)
![00006](https://user-images.githubusercontent.com/24534698/230741113-c7329faa-bc9e-4470-97fa-2136ffff1ccf.png)
![00007](https://user-images.githubusercontent.com/24534698/230741114-fb41e016-d043-41a4-9a2f-d639ec6679cc.png)
![00008](https://user-images.githubusercontent.com/24534698/230741116-cdd1635d-6d69-4efe-83b4-52d80600289c.png)

**Comment by alexfredo** [comment]
Im really impress by the result your script is clearly awesome I can't wait to have fixed the darker images bug

**Comment by volotat** [comment]
Cannot say anything regarded the web-ui error, but it might be related to the darkening as I never experienced it myself while working on the script.

**Comment by alexfredo** [comment]
every render it's write : 
Error running process: C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\AUTOMATIC1111\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 628, in process
    unit = self.parse_remote_call(p, unit, idx)
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 540, in parse_remote_call
    unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
AttributeError: 'str' object has no attribute 'enabled'


I found someone else have the same error message : https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9107

**Comment by volotat** [comment]
Did you made ControlNet accessible through API in the settings?

**Comment by alexfredo** [comment]
my controlnet settings : 
![controlnetsettings](https://user-images.githubusercontent.com/24534698/230742337-b26ab9a2-de8a-4cbe-ac68-226dd11032dd.PNG)

**Comment by volotat** [comment]
Ok. It seems like a bug in web-ui. You can do the following: go to modules/api/api.py in web-ui and replace this string (it should be at 275 line)
`script_args[alwayson_script.args_from:alwayson_script.args_to] = request.alwayson_scripts[alwayson_script_name]["args"]`
with this:
```
for idx in range(0, min((alwayson_script.args_to - alwayson_script.args_from), len(request.alwayson_scripts[alwayson_script_name]["args"]))):
                        script_args[alwayson_script.args_from + idx] = request.alwayson_scripts[alwayson_script_name]["args"][idx]
```
Please tell me if it's helped.

**Comment by alexfredo** [comment]
Thanks it's fixed the webui error message ! but I have always the picture become more and more darker there's another message in the cmd of the script : 
![message2](https://user-images.githubusercontent.com/24534698/230742916-09e0250a-bf77-4005-814a-5464a07bb30a.PNG)

**Comment by volotat** [comment]
Just a warning, you can ignore it. No idea why it is darkening though.

**Comment by alexfredo** [comment]
It's very frustrating your script have a awesome temporal consistency I really want to use it

**Comment by alexfredo** [comment]
Im forced to add "--no-half-vae" for generate the video maybe it's because of that ?

**Comment by alexfredo** [comment]
it's seems to be a problem with the vae https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6858

**Comment by alexfredo** [comment]
It solved the problem I have downloaded the vae for the checkpoint I use, Thanks you for the helps !

**Comment by alexfredo** [comment]
There's a little bit of flicker but with the davinci resolve deflicker it's fix the problem :)

**Comment by alexfredo** [comment]
I have a last question does it works with LoRA ? thanks
