### ISSUE TITLE
Any way to speed it up? its running  5-10x slower than regular generation

### ISSUE THREAD

**Issue by theseraphim** [volotat/SD-CN-Animation#10]
14seconds per it on a 512x768 video.

Is there anything that can be done to speed it up?

**Comment by volotat** [comment]
There is multiple processing happening for each frame alongside optical flow estimation. This is the main reason of slow down. Right now speeding up the process is not a main priority but achieving best possible results at multiple domains with strong stylization. There is a huge room for optimization, but this will be a concern for much later. And most likely this would require to unbind from the Automatic1111 web-ui, so I would have to reimplement many of its features.

**Comment by theseraphim** [comment]
fair comment, i was hoping for a "oh youve forgotten this step" but i can see it being computationally expensive.
