### ISSUE TITLE
exception occur and quit at the first frame

### ISSUE THREAD

**Issue by flowinginthewind700** [volotat/SD-CN-Animation#11]
script.py", line 235, in <module>
    _, alpha_mask, warped_styled = RAFT_estimate_flow_diff(prev_frame, frame, prev_frame_styled)
  File "D:\study\SD-CN-Animation\script.py", line 135, in RAFT_estimate_flow_diff
    diff_mask = np.abs(warped_frame.astype(np.float32) - frame2.astype(np.float32)) / 255
ValueError: operands could not be broadcast together with shapes (872,488,3) (866,486,3)

**Comment by yongtaof** [comment]
sorry I find the reason is the width and  height is set to wrong value
