### ISSUE TITLE
Offline?

### ISSUE THREAD

**Issue by Johnnyprim3** [volotat/SD-CN-Animation#112]
Hi Bro, enjoying your work...I however noticed it doesn't seem to work offline? Is there a way around this or would you know a way to use A1111 offline so as to be able to use this beautiful extension? 
Thanks for your time.
Cheers

**Comment by volotat** [comment]
What do you mean offline? I don't quite get you.

**Comment by Johnnyprim3** [comment]
> What do you mean offline? I don't quite get you.

I mean use the extension + A1111 if you're without an internet connection. Since SD-CN requires scikit-image==0.19.2 each time you boot up the web ui (Thanks for responding fast)

**Comment by volotat** [comment]
It should not require to install it each time you run it, just for the first time. But there might be a problem, I will take a look.

**Comment by volotat** [comment]
Should not be an issue anymore.

**Comment by Johnnyprim3** [comment]
> Should not be an issue anymore.

Thanks Brother...Your work is A GIFT TO MY CREATIVITY

**Comment by Ainaemaet** [comment]
Just coming to give a hearty THANK YOU as well. SD-CN-Animation is absolutely wonderful and it's so great to see it continuing to develop and evolve (though I still have some difficulty stopping my gens from turning blockier the further it goes lol.
