### ISSUE TITLE
How to use video 2 video to generate an effect like watercolor

### ISSUE THREAD

**Issue by Websteria** [volotat/SD-CN-Animation#116]
When I try to do a video to video with the prompt watercolor painting, it seems like the video is mostly SD trying to find watercolor paintings in my video. It does not take the video and make it look like all the samples I've seen. Anyone else had this experience? This is 8 frames in. Frame one is a straight up painting that has nothing to do with the video at all.
![00008](https://github.com/volotat/SD-CN-Animation/assets/3253286/55626d75-5211-48b0-b6c3-276c201b935a)

**Comment by volotat** [comment]
Please check out this examples: https://drive.google.com/drive/folders/1eFz7A6yBcX10yM_3-sKjbvVdcjGiHras many of these demos contains exact parameters used to create them. I hope it will help.
