### ISSUE TITLE
Some details about parameters

### ISSUE THREAD

**Issue by koren-v** [volotat/SD-CN-Animation#118]
Hi, folks, nicely done!)

I wonder if is it possible to read somewhere about your approach to get an understanding of hyperparameters and their impact on generation?

**Comment by volotat** [comment]
There is a discussion about this here: https://github.com/volotat/SD-CN-Animation/discussions/43 There are no paper if you asking about this. At least not yet.

**Comment by koren-v** [comment]
Thanks!
