### ISSUE TITLE
Extension is joining two things, not making two thins

### ISSUE THREAD

**Issue by mdlieber99** [volotat/SD-CN-Animation#128]
When I use the extension and enter

A beach AND a pizza AND a basketball 

I get the  image here - half pizza half basketball, rather than one of each in their zones.  I'm working with the default settings that give you a left and right zone.  I never get both in their own zones.  Any ideas?

![00382-888849083-1](https://github.com/volotat/SD-CN-Animation/assets/105756477/23b0af88-3e21-49ec-ac25-4adeaa3e95b7)

**Comment by volotat** [comment]
This is not related to the extension but to Stable Diffusion itself. And I couldn't say it is even a bug, just the way how SD sometimes works.
