### ISSUE TITLE
Conflict with Dyanmic Prompt extention

### ISSUE THREAD

**Issue by haik74** [volotat/SD-CN-Animation#141]
Hi, in my case, after install I can see 2 tabs for wildcard manager.

**Comment by volotat** [comment]
Please, look this issue: https://github.com/volotat/SD-CN-Animation/issues/88

**Comment by haik74** [comment]
ok I remove the stable-diffusion-webui-two-shot folder from extentions, lets see if this helps

**Comment by haik74** [comment]
no , its remove double tab , but not show the SD ANIMATION TAB

**Comment by efraxs** [comment]
anyway to fix this? i have the same problem and doesnt have the two shot extension
