### ISSUE TITLE
Module 'gradio' has no attribute 'Code'

### ISSUE THREAD

**Issue by Malakid21** [volotat/SD-CN-Animation#147]
I install SD-CN-Animation and after restart i get this error. 
![image](https://github.com/volotat/SD-CN-Animation/assets/87801568/765ba1d2-b068-479c-b537-56c431460656)

**Comment by Malakid21** [comment]
I did an up date, unfortunately the problem remains ;/

**Comment by volotat** [comment]
You may try to update gradio manually with  
`pip install gradio --upgrade`
only make sure that you do this inside webui environment

**Comment by Malakid21** [comment]
I installed and still

Error executing callback ui_tabs_callback for D:\AI\stable-diffusion-webui\extensions\SD-CN-Animation\scripts\base_ui.py
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\modules\script_callbacks.py", line 120, in ui_tabs_callback
    res += c.callback() or []
  File "D:\AI\stable-diffusion-webui\extensions\SD-CN-Animation\scripts\base_ui.py", line 179, in on_ui_tabs
    export_setting_json = gr.Code(value='')
AttributeError: module 'gradio' has no attribute 'Code'

**Comment by volotat** [comment]
@Malakid21 Your gradio still outdated for some reason. This is the only reason why there is no 'Code' attribute. But can't say how to fix this in your case as I have no idea what may cause it.

**Comment by Malakid21** [comment]
@volotat 
I find solution, i have "Inpaint Anythink" and i add some class that colide, i edit this and now all work. 
Thx for help :)
