### ISSUE TITLE
IS THERE A PLACE TO UPLOAD STRICTLY SD-CN ANIMATION?

### ISSUE THREAD

**Issue by Johnnyprim3** [volotat/SD-CN-Animation#186]
Hi fellow creators...I wonder if there was a discord or a forum where WE could upload animation made with this Mind-boggling wonder of a tool? For inspiration, networking amongst artists or even PUBLICITY. More folks need to know this exists. Everyone is (all of a sudden) going crazy about Image to Video, when SD-CN has the BEST Image 2 Video function out there... it's my favorite aspect of the whole tool.
I just feel we need to band together to ENJOY this tool even from another artist's perspective.
Thanks and Happy Creating.

**Comment by Duemellon** [comment]
unfortunately it stopped working in A1111 with the latest updates to ControlNet. We need a fix from the creator : (

**Comment by Johnnyprim3** [comment]
> unfortunately it stopped working in A1111 with the latest updates to ControlNet. We need a fix from the creator : (

But I'm using it right now...granted, I don't use Control net
