### ISSUE TITLE
There's a ghosting problem when the animation is on the same plan for too long.

### ISSUE THREAD

**Issue by alexfredo** [volotat/SD-CN-Animation#2]
Hi the script is awesome but do you know how I can fix the ghosting problem ? thanks

**Comment by volotat** [comment]
I'm working on trying to solve ghosting issue. It became much less noticeable with additional processing, but for now it seems very hard to get rid of it completely.

**Comment by alexfredo** [comment]
Thanks for all the hard work, I try to post all my test with the script on reddit I hope it's will bring more attention to your work
Here some test I made : 
https://www.reddit.com/r/StableDiffusion/comments/12hacuk/hes_possible_to_make_beautiful_anime_movie_with/
https://www.reddit.com/r/StableDiffusion/comments/12h7ilw/testing_the_temporal_consistency_of/
https://www.reddit.com/r/StableDiffusion/comments/12gaq06/jenna_ortega_sings_never_gonna_give_you_up/
https://www.reddit.com/r/StableDiffusion/comments/12g1e00/wow_crazy_temporal_consistency_using/

**Comment by volotat** [comment]
Yeah, I've seen your results and they are incredible.
