### ISSUE TITLE
Help with running it

### ISSUE THREAD

**Issue by Niutonian** [volotat/SD-CN-Animation#20]
Hello, I would like to know if someone could help me figure out why I keep on getting the same mistake multiple time related to torch

Here is my issue, When I run the line below, I get the module torch not found even though it is there. 

'D:\stable-diffusion-webui\SD-CN-Animation>python3 compute_flow.py -i "C:\Users\Arnaud***\Downloads\Remove0417_720p.mov" -o "D:\stable-diffusion-webui\SD-CN-Animation\EXPORT" -v -W 720 -H 540
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\SD-CN-Animation\compute_flow.py", line 7, in <module>
    from flow_utils import RAFT_estimate_flow
  File "D:\stable-diffusion-webui\SD-CN-Animation\flow_utils.py", line 9, in <module>
    import torch
ModuleNotFoundError: No module named 'torch' '

What could be the problem?

**Comment by jAyATJaY** [comment]
Did you install the prerequisites?

**Comment by Cubey42** [comment]
are you running it inside the environment of your sd?

**Comment by Niutonian** [comment]
Yes all the prerequisites are installed but I am running it inside of the env of SD, 
Should I setup a conda env for it, 
sorry I'm really new at all of this

**Comment by CaptnSeraph** [comment]
i would setup a separate environment for raft, there are different torch versions across all these ML projects and ive never been able to get them working outside of individual environments

**Comment by Niutonian** [comment]
Ok, thanks all for the tips, I will try again to run it,
