### ISSUE TITLE
[BUG] I have a duplication moving images with the v0.5

### ISSUE THREAD

**Issue by alexfredo** [volotat/SD-CN-Animation#21]
Hi I have a weird bug with the v0.5 is someone know what is it ? thanks 

https://user-images.githubusercontent.com/24534698/233007148-3bd9a50e-4a88-4647-b07d-2d532b2f0575.mp4

**Comment by Cubey42** [comment]
yeah I'm getting this also, why does it ghost so much?

**Comment by Cubey42** [comment]
![image](https://user-images.githubusercontent.com/51013227/233222473-cc2398b2-58c2-433d-8ede-8110e5d3c8f2.png)

**Comment by volotat** [comment]
Yeah. There is an issue. I will try to fix it soon, but I can't locate the problem just yet.

**Comment by volotat** [comment]
It seems that the problem is inside background removing process. I haven't find the solution yet, but I added -rb flag in the compute_flow.py script so it could be easily turned on or off.

**Comment by CaptnSeraph** [comment]
yeah, that background removal was really a bodge, im not happy with its performance, its real buggy. if only runwayml had their model available lol

**Comment by alexfredo** [comment]
Maybe it's can help for the background removal : https://github.com/continue-revolution/sd-webui-segment-anything

**Comment by alexfredo** [comment]
There's a version for video https://github.com/gaomingqi/Track-Anything
