### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by Tobe2d** [volotat/SD-CN-Animation#22]
Any guide on how to run it on windows?

**Comment by Cubey42** [comment]
it works for me on windows using the guide

**Comment by volotat** [comment]
It should be exactly the same as with Linux, although I have not tried to run it on windows myself.

**Comment by CaptnSeraph** [comment]
try using it under miniconda in a virtual environment, helps keep requirements together

**Comment by jAyATJaY** [comment]
I'm running it on Windows 10. With an Nvidia 40 series card it runs perfectly. Following the instructions in the readme should help.
