### ISSUE TITLE
Issue with Submitting

### ISSUE THREAD

**Issue by scrambled2** [volotat/SD-CN-Animation#27]
I've triple checked everything and even tried with a fresh install of webui and a rollmarch to pre March 25th as well. No matter what I get errors. 

(sdoptical) PS D:\Github\SD-CN-Animation> python vid2vid.py
  0%| 
Traceback (most recent call last):
  File "D:\Github\SD-CN-Animation\vid2vid.py", line 175, in <module>
    out_image = controlnetRequest(to_b64(frame), to_b64(frame), PROCESSING_STRENGTH, w, h, mask = None).sendRequest()
  File "D:\Github\SD-CN-Animation\vid2vid.py", line 123, in sendRequest
    image_bytes = base64.b64decode(data_js["images"][0])
KeyError: 'images'

Any ideas?

**Comment by volotat** [comment]
It seems there is a bug in new version of web-ui. It already been discussed in another issue. Basically the solution is the following: go to modules/api/api.py in web-ui and replace this string (it should be at 275 line)
```
script_args[alwayson_script.args_from:alwayson_script.args_to] = request.alwayson_scripts[alwayson_script_name]["args"]
```
with this:
```
for idx in range(0, min((alwayson_script.args_to - alwayson_script.args_from), len(request.alwayson_scripts[alwayson_script_name]["args"]))):
    script_args[alwayson_script.args_from + idx] = request.alwayson_scripts[alwayson_script_name]["args"][idx]
```
