### ISSUE TITLE
Enhancements: Time left for completion 

### ISSUE THREAD

**Issue by rezponze** [volotat/SD-CN-Animation#30]
Hey, thanks for doing the awesome work of re-writing the code to make it into an Auto1111 extension. This is great. I'm already trying it and I love how streamlined now the process is. <3

Just a minor thing, In the previous command line version I remember some timer that told me how much time was going to take. 
Would it be possible to add "Time elapsed/left" next to "Frames prepared" / "Frames processed"? 

Anyways, love the new extension, thanks for this!

**Comment by volotat** [comment]
Yes, I will do that. That would be a very helpful feature. Thank you for a proposal.
