### ISSUE TITLE
vid2vid

### ISSUE THREAD

**Issue by MeTheMagnificent** [volotat/SD-CN-Animation#32]
On trying vid2vid conversion, I get this error. Not sure what I'm doing wrong.

![image](https://user-images.githubusercontent.com/59197916/236743686-2e035590-e9b7-4a47-8910-283dda8ed379.png)

![image](https://user-images.githubusercontent.com/59197916/236743893-990de11f-e845-401d-918c-3c01ab70a651.png)

This happens with or without controlnet enabled.  Also a question on controlnet. Can you just use the input directory for controlnet ? Or do you have to export the video as frames and feed it to the batch controlnet ?

**Comment by volotat** [comment]
Not sure about the error. Try to process any other video, preferably mp4 with H.264 codec, as I suspect that this is some sort of problem with the video itself. Regarding controlnet, you have not to do any extra steps besides just activating it and choosing the model, the current frame will be fed to the CN by the extension itself.

**Comment by alexmihaic** [comment]
Same happens to me:

A1111 Web UI Autoinstaller\stable-diffusion-webui/extensions/sd-cn-animation/scripts\core\txt2vid.py", line 62, in start_process
    processed_frame = np.array(processed_frames[0])
IndexError: list index out of range

**Comment by alexmihaic** [comment]
Changing the video worked for me, thanks!

**Comment by MeTheMagnificent** [comment]
I got a number of things wrong that time. Messed up height and width input, also the video was 5 minutes long lol. I exported a shorter 5 second video and made sure it was h.264 mp4. Still didn't work, BUT I restarted webui completely and now it works. So it's solved ! 

Thanks !
