### ISSUE TITLE
CLI or Compatibility with Remote Instance

### ISSUE THREAD

**Issue by svupper** [volotat/SD-CN-Animation#4]
I'm currently running AUTOMATIC1111 from a Docker container on a remote instance.
seems like the script doesn't work since it's trying to show image with OpenCV and I have no UI on my Ubuntu instance. is it possible to run it with no display or with web interface instead ?

**Comment by volotat** [comment]
Remove these lines from the script:
`cv2.namedWindow('Out img')`
and
`  cv2.imshow('Out img', img_show)
  if cv2.waitKey(1) & 0xFF == ord('q'): exit() # press Q to close the script while processing
`
Everything should work fine. It does showing images, but only for debugging purposes.

**Comment by svupper** [comment]
Thanks! The scripts is nice but takes a lot of time to render
