### ISSUE TITLE
Fix usage of deprecated arguments

### ISSUE THREAD

**Issue by tr7zw** [volotat/SD-CN-Animation#40]
On automatic1111 there is currently this warning on each frame in the console
> sd-cn-animation/scripts\core\vid2vid.py:115: FutureWarning: `multichannel` is a deprecated argument name for `match_histograms`. It will be removed in version 1.0. Please use `channel_axis` instead.

On https://github.com/vladmandic/automatic this deprecated argument has already been removed, causing the script to fail at the first step.

**Comment by volotat** [comment]
Got it. Will fix it in the next version.

**Comment by volotat** [comment]
Should be fixed in v0.8. Please open new issue if the error still occurs.

**Comment by tr7zw** [comment]
Yep, works now on Automatic.
