### ISSUE TITLE
Suspend/Resume processing

### ISSUE THREAD

**Issue by buckwheaton** [volotat/SD-CN-Animation#49]
I'm using Google Colab, which will kick me off after a period of time and, often, the integration with Google Drive just breaks out of nowhere.  I'm currently running a larger-format v2v and it's taking hours (for just 60 frames).  Which is fine, but I'm a bit paranoid about losing progress if I get kicked off of free Colab and/or if something breaks.  

It would be wonderful to be able to manually save progress mid-generation (or automatically save every X frames) and be able to resume later.  I suspect something like this would be nice for other setups/use cases as well.

Thanks for making this.  It's awesome.

**Comment by volotat** [comment]
Please check out the last update. There is an option now for saving frames into a folder alongside the video. I hope it will help you with your problem.

**Comment by buckwheaton** [comment]
Awesome, thank you!
