### ISSUE TITLE
slowly reverts back to the original image

### ISSUE THREAD

**Issue by Squeezitgirdle** [volotat/SD-CN-Animation#50]
Hey there, been trying a few different settings so far trying to get a feel for this.

One thing I've noticed is that the first few frames will be a new image (as intended) then it slowly fades back to the original. 
For example, a person  dancing and it's only 20 frames long, they'll start off looking like a new person, but roughly halfway through the video won't look much different from the original gif. By the end it'll look almost exactly the same.

This happens less often when frame strength is above 0.5 but then the videos get more wild.
Attempting processing strength around 0.65, and 0.25
Haven't really figured a good setting to try and retain the original image but replace the character used.

Tested a video with 18 frames, brown haired girl dancing.

Frames 1 - 10 start with a girl with short orange hair and a hat, but slowly fade, by frame 10 it looks exactly the same as the original gif. Long brown haired girl again.

**Comment by Squeezitgirdle** [comment]
Raising "fix frame strength" seems to partially solve the reverting back to original video issue. However then you end up with wildly different videos than the original. 

This may be a simple misunderstanding of how to properly use this. 
However fix frame strength at 0 has a wildly different image.

Fix frame strength at 75 has a mostly different image, but occasionally the original.

Processing Strength at 0 or 1 don't seem to make any difference, I can't really figure out what this is doing. 
Putting both at 0 or putting both at 1 do not result in the original image either.

**Comment by ouoertheo** [comment]
I think I've been getting the same thing with vid2vid. Generates the first frame as expected, then each subsequent image is just a frame of the new image fading into the original first frame of the input video.

**Comment by volotat** [comment]
First frame will always be a little bit better, as it is the only frame generated directly from the initial image without influence of the previous frame and the occlusion mask. But after that all other frames should have roughly the same stylization intention.
Check out this discussion, I hope this will help you to get better results: [#80 (comment)](https://github.com/volotat/SD-CN-Animation/discussions/80#discussioncomment-5879239)
