### ISSUE TITLE
All frames processed by vid2vid, but no video generated

### ISSUE THREAD

**Issue by andypotato** [volotat/SD-CN-Animation#52]
I'm trying to process a short 5 second video using vid2vid + ControlNet. It seems to work fine and it will process all 150 frames.

However when it's done, nothing will happen. I was expecting to get some kind of download link to download the result, just I can't find anything on the UI. Also there are no errors reported anywhere on the UI or the Stable Diffusion console.

Am I just blind or is that some kind of bug?

**Comment by highjohnconquer** [comment]
no I'm having the sameproblem

**Comment by highjohnconquer** [comment]
you can check your out[ut files but i'm just getting a 1kb file that won't play anything

**Comment by andypotato** [comment]
I found the videos in the output/vid2vid folder. So there is no technical problem here.

Seems more like a UI issue, cause there is no indication what to do after a video was processed. Also the docs don't mention that you need to check the output folder. Maybe this could be improved?
