### ISSUE TITLE
'Need to enable queue to use generators.' error - when running txt2vid

### ISSUE THREAD

**Issue by glennamarshall** [volotat/SD-CN-Animation#56]
Traceback (most recent call last):
  File "C:\Users\ga_ma\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\ga_ma\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\Users\ga_ma\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 843, in call_function    raise ValueError("Need to enable queue to use generators.")
ValueError: Need to enable queue to use generators.

**Comment by shorties** [comment]
im encountering the same error while trying to run vid2vid

**Comment by Bigtoecutter** [comment]
Getting the same error :( Both txt to vid and vid to vid. Worked on a different machine earlier...

**Comment by volotat** [comment]
I've seen people solving this issue by updating webui interface to the latest version. I will recommend trying to do the same.

**Comment by Bigtoecutter** [comment]
> I've seen people solving this issue by updating webui interface to the latest version. I will recommend trying to do the same.

Updating the version of automatic 1111 has worked. However, I think the latest version has too many control net methods and the scribble_hed pre processor doesn't get the same continuity like the control_sd15_hed pre processor that is in my older version of automatic 1111 installed about a month ago.

**Comment by glennamarshall** [comment]
still doesn't work for me - I have 'git pull' in my .bat file, so it should always be the latest version of the webui.

**Comment by glennamarshall** [comment]
i installed a fresh version of auto 1111 and it works.. so something to do with dependencies i suspect.. will close issue after a while incase anyone has any thoughts of what the source problem might be.

**Comment by lsjspl** [comment]
如果启动命令里有这个参数的话：--no-gradio-queue
删除就可以了

**Comment by Agnyy** [comment]
I applied the "Git pull" command and it still didn't work.
![image](https://github.com/volotat/SD-CN-Animation/assets/25137502/4a07155d-5464-47f5-8637-5ba3d4758291)

**Comment by lsjspl** [comment]
> I applied the "Git pull" command and it still didn't work. ![image](https://user-images.githubusercontent.com/25137502/237399329-4a07155d-5464-47f5-8637-5ba3d4758291.png)

你可以先执行(step 1)：
git remote set-url origin  https://github.com/AUTOMATIC1111/stable-diffusion-webui
然后再(step 2):
git pull

**Comment by glennamarshall** [comment]
fresh install of auto 1111 fixes this problem.
