### ISSUE TITLE
All videos take on a purple or reddish hue. There seems to be no option which stops this. Anyone know the fix for this?

### ISSUE THREAD

**Issue by Websteria** [volotat/SD-CN-Animation#57]
All of the txt2vid videos I do start turning purple or red after a few frames. Any ideas what could be causing this?

**Comment by durrtydurr** [comment]
Same issue here as well. Happens with every prompt I enter in Text to Video.

**Comment by volotat** [comment]
There was an issue with color matching technique. It should work much better now.
