### ISSUE TITLE
webui extension

### ISSUE THREAD

**Issue by gitmylo** [volotat/SD-CN-Animation#6]
Hey, i think this script would work better as an extension inside of the Automatic1111 webui. preferably as a script you can choose under img2img in the script dropdown.
then you would upload a video and it would end up in a temporary folder, it renders it, then recombines the frames.

i think this script would be a lot more user friendly if it was available from the Automatic1111 webui, and it doesn't seem to have a good reason to be a separate script, as it requires the Automatic1111 webui to function.

and if you decide not to, i could do it if you wanted me to.

**Comment by theseraphim** [comment]
you could still use the API, but have the calls within the gradio server, its only a matter of passing arguments to the vid2vid.py and then running the script, if you want, i can take a look at the setup and see how it could be implemented, i have nothing to do tomorrow and really need to get my github active again lol

**Comment by volotat** [comment]
Hm.. I never realized that might be that simple. I probably should take a closer look at how other extensions are built. Although I have one concern. Web-ui constantly keeps weights of the current SD model in the VRAM, and flow estimation also requires a lot of VRAM. Is there any way to unload an SD model from web-ui while the flow is computing?

**Comment by theseraphim** [comment]
I think you can call unloadapi (line 480 in the api.py in a1111) 

`    def unloadapi(self):
        unload_model_weights()

        return {}`
which does this 
`def unload_model_weights(sd_model=None, info=None):
    from modules import lowvram, devices, sd_hijack
    timer = Timer()

    if shared.sd_model:

        # shared.sd_model.cond_stage_model.to(devices.cpu)
        # shared.sd_model.first_stage_model.to(devices.cpu)
        shared.sd_model.to(devices.cpu)
        sd_hijack.model_hijack.undo_hijack(shared.sd_model)
        shared.sd_model = None
        sd_model = None
        gc.collect()
        devices.torch_gc()
        torch.cuda.empty_cache()

    print(f"Unloaded weights {timer.summary()}.")

    return sd_model`

and then you can call  reloadapi

`    def reloadapi(self):
        reload_model_weights()

        return {}`

looks like it does whats necessary, im not familiar with the api process, but this is probably where you reference loading/unloading

**Comment by wordbrew** [comment]
I really hope you two collaborate more and make this into an extension. It would be amazing.

**Comment by CaptnSeraph** [comment]
If you look in the A1111 settings under actions, there are buttons for unloading and reloading the checkpoint for VRAM purposes... so if gradio can call that, so could your script, using the code i pointed to above.. just need to workout how to call functions from the webui

**Comment by volotat** [comment]
@CaptnSeraph Thanks for the hint. Already working on it. Usable version should be available in a couple days, if there would not be some critical bugs.
![Screenshot from 2023-04-23 14-25-04](https://user-images.githubusercontent.com/14307880/233837205-37881ac1-acca-40a9-a029-34eadba1f582.png)

**Comment by volotat** [comment]
I'm happy to say that the extension is finally available to try but only on the 'dev' branch for now.  I decided not to go with the API route and make a proper extension that relies on the internal methods to not waste time on the API call and have much more control of the processes. Unfortunately it took quite more time than I expected to learn the internal structure of web-ui and control-net extension to make it actually work and rewrite the code. Right now only the 'vid2vid' tab is working. There is still one major problem that I haven't been able to solve yet. Right now to make ‘SD-CN-Animation’ extension work properly you will have to modify 'extensions/sd-webui-controlnet/scripts/controlnet.py' file from the ControlNet extension to this code: https://pastebin.com/K8knbXy8. It should be possible to fix this issue in a way that was described in this discussion https://github.com/Mikubill/sd-webui-controlnet/discussions/1095. This issue is the main reason to keep new code in another branch while I’m trying to fix this problem.

**Comment by wordbrew** [comment]
Thanks! I will install a new server and check this out.

**Comment by wordbrew** [comment]
Don't mind my ignorance here. I might be doing something wrong, but I tried to install the extension and can't seem to get it working.

I go to my extensions tab in A1111 and install via URL. I enter your Git repo and instruct it to install via the "dev" branch. It installs, but when I reboot gradio, it throws errors in the console stating that it can't load base_ui.py and vid2vid.py because there is no module named as 'vid2vid' and 'flow_utils'.

When the UI loads back up, there is no SD-CN-ANimation tab. It says the extension is installed, but obviously that is not the case.

I also noticed in your readme.md you have the following note:

Installing the extension

```
TODO

Download RAFT 'raft-things.pth' from here: [RAFT link] and place it into 'stable-diffusion-webui/models/RAFT/' folder. All generated video will be saved into 'outputs/sd-cn-animation' folder.
```

Seems perhaps I'm missing some steps to get the extension working properly?

**Comment by CaptnSeraph** [comment]
you would be better off posting the actual console log, it really can help

**Comment by wordbrew** [comment]
```
Error loading script: base_ui.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/SD-CN-Animation/scripts/base_ui.py", line 29, in <module>
    from vid2vid import *
ModuleNotFoundError: No module named 'vid2vid'

Error loading script: vid2vid.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/SD-CN-Animation/scripts/vid2vid.py", line 41, in <module>
    from flow_utils import RAFT_estimate_flow, RAFT_clear_memory, compute_diff_map
ModuleNotFoundError: No module named 'flow_utils'
```

**Comment by volotat** [comment]
@wordbrew Thank you for the report. I found the issue, the problem was in letter capitalization in the name of the extension. I updated the code, it should not throw these errors anymore. Please try to update or reinstall it. Regarding the 'raft-things.pth' file, it is available here https://drive.google.com/drive/folders/1sWDsfuZ3Up38EUQt7-JDTT1HcGHuJgvT . I will try to make it download automatically in the future, but I'm not quite sure yet if I am even allowed to do that.

**Comment by gitmylo** [comment]
> @wordbrew Thank you for the report. I found the issue, the problem was in letter capitalization in the name of the extension. I updated the code, it should not throw these errors anymore. Please try to update or reinstall it. Regarding the 'raft-things.pth' file, it is available here https://drive.google.com/drive/folders/1sWDsfuZ3Up38EUQt7-JDTT1HcGHuJgvT . I will try to make it download automatically in the future, but I'm not quite sure yet if I am even allowed to do that.

there's plenty of extensions that download models, including ones that are in the official list. [magic prompt](https://github.com/adieyal/sd-dynamic-prompts) for example. also [deforum, for depth and interpolation for example. and even RAFT as well](https://github.com/deforum-art/deforum-for-automatic1111-webui)

**Comment by gitmylo** [comment]
after trying out the extension, i noticed that there's no stop button.
also, another nice feature would be the ability to select the framerate, so the original video's framerate gets lowered to the selected framerate.

**Comment by wordbrew** [comment]
> @wordbrew Thank you for the report. I found the issue, the problem was in letter capitalization in the name of the extension. I updated the code, it should not throw these errors anymore. Please try to update or reinstall it. Regarding the 'raft-things.pth' file, it is available here https://drive.google.com/drive/folders/1sWDsfuZ3Up38EUQt7-JDTT1HcGHuJgvT . I will try to make it download automatically in the future, but I'm not quite sure yet if I am even allowed to do that.

Oh thank you for the help with that. I was busy looking at paths and other things thinking that it might have something to do with how I had my install set up on my colab. Of course it would be something as simple as capitalization.

The extension appears to work. Now time to test it. Thanks again.

**Comment by wordbrew** [comment]
2 steps forward, 1 step back.

I got the extension installed right. I've replaced the Controlnet.py code with the pastebin code you provided. I downloaded raft-things.pth file and put in in /stable-diffusion-webui/models/RAFT.

Things boot up well. I upload the video (2 sec clip for testing). Enter my prompt details and adjust some settings. Then click "generate" and it begins to process before spitting out the following console error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1036, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 488, in async_iteration
    return next(iterator)
  File "/content/gdrive/MyDrive/sd2/stable-diffusion-webui/extensions/SD-CN-Animation/scripts/vid2vid.py", line 168, in start_process
    processed_frames, _, _, _ = modules.img2img.img2img(*args_list) #img2img(args_dict)
  File "/content/gdrive/MyDrive/sd2/stable-diffusion-webui/modules/img2img.py", line 85, in img2img
    override_settings = create_override_settings_dict(override_settings_texts)
  File "/content/gdrive/MyDrive/sd2/stable-diffusion-webui/modules/generation_parameters_copypaste.py", line 329, in create_override_settings_dict
    for pair in text_pairs:
TypeError: 'UiControlNetUnit' object is not iterable
```

Thoughts?

**Comment by volotat** [comment]
Not sure yet. Might be a compatibility problem with the last version of web-ui. Give me a some time to figure out problems with ControlNet that I described earlier and I will try to run the code on the last web-ui version. If I will encounter something similar I probably would be able to fix this.

**Comment by wordbrew** [comment]
Makes sense. Really appreciate your dedication to this project.

**Comment by volotat** [comment]
The issue with ControlNet was fixed. I merged everything into the main branch. 

@wordbrew I tried the extension on the last version of web-ui and it did work correctly for me. Although I'm still using torch v1.13. I would recommend you to try to update/reinstall SD-CN-Animation one more time. But make sure that you are also using the latest version of 'sd-webui-controlnet' extension.

@gitmylo Thank you for your suggestions, I will try to implement it in the near future.

I'm gonna close this issue now, as the extension is now fully available, although it does require some more work to make it more user friendly. As well as an addition of txt2vid mode. If anyone will have any issue with the extension, please open a new issue dedicated to it.
