### ISSUE TITLE
Reduce image impact on vid2vid

### ISSUE THREAD

**Issue by afgonczol** [volotat/SD-CN-Animation#66]
I am trying to use a video only for posing and have the output video entirely dependent on the prompt and controlnet (using openpose). However, the vid2vid always contains a lot of the original video information (beyond the pose). There doesn't seem to be an obvious way to reduce the impact of the original video frames. I'm assuming it's using some sort of img2img, but without a way to change the denoising strength.

**Comment by volotat** [comment]
You can only do that by increasing 'Processing strength' and 'Fix frame strength'. There is no workaround as the original video plays a crucial role in providing an initial view of the frames plus optical flow and occlusion information.
