### ISSUE TITLE
Txt2Vid cfg comming up with the frames

### ISSUE THREAD

**Issue by maciekpoplawski** [volotat/SD-CN-Animation#71]
Cant pinpoint what causes this. But on some generations it looks like the cfg is increasing with the frames resulting in like "overcooked" images (to high cfg) 
Example: 

https://github.com/volotat/SD-CN-Animation/assets/54249329/f377c48f-3fd1-45da-90b8-8c4145ecceff

**Comment by maciekpoplawski** [comment]
Ahhhhhhh... this is another topic. Generated mp4 are "broken" - as you can see above - cant be played + cant be uploaded in for example WhatsApp "wrong video format"

same video after reconverting it in vlc to mp4:

https://github.com/volotat/SD-CN-Animation/assets/54249329/1888f647-c984-4664-a4ca-3b901e46a281

**Comment by volotat** [comment]
It might happen if you use fixed seed to generate the video. Was this the case here?

**Comment by maciekpoplawski** [comment]
Boom headshot! Yes i used fixed seed. Is there a way to fix it? What could cause that? Maybe i could help in this part?

**Comment by maciekpoplawski** [comment]
![image](https://github.com/volotat/SD-CN-Animation/assets/54249329/5f0cad3b-e80c-44e3-84cf-4094b51c0fc5)

**Comment by maciekpoplawski** [comment]
![giphy](https://github.com/volotat/SD-CN-Animation/assets/54249329/7055df0b-915c-4527-985a-5c10f00329e0)
