### ISSUE TITLE
[UI issue]there‘s two“Wildcards Manager”tab（Manage wildcards for Dynamic Prompts） after installed this extension！

### ISSUE THREAD

**Issue by yin3331** [volotat/SD-CN-Animation#88]
look the picture：
![屏幕截图 2023-05-13 103848](https://github.com/volotat/SD-CN-Animation/assets/32604161/8dc35efd-cf41-40e8-a88d-75344841263e)

**Comment by volotat** [comment]
Most likely the problem is not related to SD-CN-Animation and is the issue of the WM extension.

**Comment by chenshaoju** [comment]
Sorry for my English.

I'm from Google Search to here.

This issue looks like `Wildcards Manager`'s issue, It same happened on [stable-diffusion-webui-two-shot](https://github.com/opparco/stable-diffusion-webui-two-shot) extension, see: https://github.com/opparco/stable-diffusion-webui-two-shot/issues/52 .

please follow up here: https://github.com/adieyal/sd-dynamic-prompts/issues/429

**Comment by Rojinski** [comment]
It's a problem with the "two shot" extension. Go to your web ui directrory / extensions  and delete the "two shot" directory and everything will be fine again.

**Comment by chenshaoju** [comment]
I don't have `two shot` folder in the extensions folder, or the whole system/storage.

this is odd. :/
![Snipaste_2023-05-18_18-25-56](https://github.com/volotat/SD-CN-Animation/assets/515763/ba9fb555-a282-4f26-9cac-cbec712a3c08)

**Comment by jlitz** [comment]
yes no two shot ext folder in my ext folder--- diabling SD CN animation ext  solves double wildcard manager tab  fwiw
