### ISSUE TITLE
new to text2video

### ISSUE THREAD

**Issue by westorix** [volotat/SD-CN-Animation#90]
after instaling it i got this error on evry frame of generation:
TypeError: Script.process() missing 8 required positional arguments: 'enabled', 'targets_', 'weight', 'disable_neg', 'strong', 'padding', 'intp', and 'debug'
and once it finishesh stiching the video toghether the webui freezes and is unresponsive.

**Comment by volotat** [comment]
Most likely related to this issue https://github.com/volotat/SD-CN-Animation/issues/86 There is a fix already in pull requests but it is not yet merged into the code as required some more testing.

**Comment by volotat** [comment]
The issue should be resolved now.
